const Loc1EndOptions = [
  {
    number: "[end]",
    group: "loc1-end",
    in_index: "loc1-end-1",
    line_index: "link-line-loc1-end-1",
    x: 1509,
    y: 644,
    width: 30,
    in_local: "loc1",
    in_pos_x: "end",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[connect]",
    group: "loc1-end",
    in_index: "loc1-end-1",
    line_index: "connect-line-loc1-end-1",
    x: 1050,
    y: -25,
    width: 250,
    in_local: "loc1",
    in_pos_x: "end",
    in_number: "1",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
];

export default Loc1EndOptions;
