const Loc1Left1400Options = [
  {
    number: "[5]",
    group: "loc1-left",
    in_index: "loc1-1400-5",
    line_index: "link-line-loc1-1400-5",
    x: 930,
    y: 106,
    width: 12,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[4]",
    group: "loc1-left",
    in_index: "loc1-1400-4",
    line_index: "link-line-loc1-1400-4",
    x: 962.5,
    y: 51.5,
    width: 8,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[3]",
    group: "loc1-left",
    in_index: "loc1-1400-3",
    line_index: "link-line-loc1-1400-3",
    x: 995,
    y: -3,
    width: 8,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[2]",
    group: "loc1-left",
    in_index: "loc1-1400-2",
    line_index: "link-line-loc1-1400-2",
    x: 1027.5,
    y: -57.5,
    width: 9,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[1]",
    group: "loc1-left",
    in_index: "loc1-1400-1",
    line_index: "link-line-loc1-1400-1",
    x: 1060,
    y: -112,
    width: 8,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "1",
    rotate: "hor",
    animation: "forward",
    line_type: "link-line",
    in_status: "disabled",
  },
  //conect lines
  {
    number: "[5]",
    group: "loc1-left",
    in_index: "loc1-1400-5",
    line_index: "connect-line-loc1-1400-5",
    x: 1273,
    y: 418,
    width: 62,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "5",
    rotate: "ver",
    animation: "reverse",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[4]",
    group: "loc1-left",
    in_index: "loc1-1400-4",
    line_index: "connect-line-loc1-1400-4",
    x: 1335,
    y: 418,
    width: 63,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "4",
    rotate: "ver",
    animation: "reverse",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[3]",
    group: "loc1-left",
    in_index: "loc1-1400-3",
    line_index: "connect-line-loc1-1400-3",
    x: 1398,
    y: 418,
    width: 29,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "3",
    rotate: "ver",
    animation: "reverse",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[2]",
    group: "loc1-left",
    in_index: "loc1-1400-2",
    line_index: "connect-line-loc1-1400-2",
    x: 1427,
    y: 418,
    width: 34,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "2",
    rotate: "ver",
    animation: "reverse",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1]",
    group: "loc1-left",
    in_index: "loc1-1400-1",
    line_index: "connect-line-loc1-1400-1",
    x: 1462,
    y: 418,
    width: 64,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "connect-line",
    in_status: "disabled",
  },
  //start-link-line
  {
    number: "[start-link-line]",
    group: "loc1-left",
    in_index: "loc1-1400-1",
    line_index: "start-link-line-loc1-1400",
    x: 1019,
    y: -27.5,
    width: 12,
    in_local: "loc1",
    in_pos_x: "1400",
    in_number: "1",
    rotate: "hor",
    animation: "forward",
    line_type: "start-link-line",
    in_status: "disabled",
  },
];

export default Loc1Left1400Options;
