// const calLoc1LeftConnectVerLine = () => {
//   let column = 0;
//   let row = 0;
//   let maxColumn = 5;
//   let maxRow = 6;
//   let x = 0;
//   let y = 0;
//   let increaseX = -57;
//   let increaseY = +33.5;
//   let spaceBetweenX = +35.3;
//   let spaceBetweenY = -60.5;

//   let startX = 858;
//   let startY = 310;

//   let result = [];

//   x = startX;
//   y = startY;
//   for (row = 0; row < maxRow; row++) {
//     x = startX + row * spaceBetweenX;
//     y = startY + row * spaceBetweenY;
//     result.push({
//       number: `[${row + 1}-${column + 1}]`,
//       group: "loc1-left",
//       in_index: `loc1-${200 * (row + 1)}-${column + 1}`,
//       line_index: `connect-loc1-${200 * (row + 1)}-${column + 1}`,
//       x: x,
//       y: y,
//       width: 90,
//       in_local: "loc1",
//       in_pos_x: `${200 * (row + 1)}`,
//       in_number: `${column + 1}`,
//       rotate: "hor",
//       animation: "forward",
//       line_type: "connect-line",
//       in_status: "disabled",
//     });
//   }
//   console.log("라인라인");
//   console.table(result);
//   return result;
// };

const Loc1LeftConnectOptions = [
  {
    number: "[1-1]",
    group: "loc1-left",
    in_index: "loc1-200-2",
    line_index: "connect-loc1-200-2",
    x: 857,
    y: 310,
    width: 90,
    in_local: "loc1",
    in_pos_x: "200",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[2-1]",
    group: "loc1-left",
    in_index: "loc1-400-2",
    line_index: "connect-loc1-400-2",
    x: 894,
    y: 249.5,
    width: 87,
    in_local: "loc1",
    in_pos_x: "400",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[3-1]",
    group: "loc1-left",
    in_index: "loc1-600-2",
    line_index: "connect-loc1-600-2",
    x: 928.6,
    y: 189,
    width: 90,
    in_local: "loc1",
    in_pos_x: "600",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[4-1]",
    group: "loc1-left",
    in_index: "loc1-800-2",
    line_index: "connect-loc1-800-2",
    x: 964,
    y: 128.5,
    width: 88,
    in_local: "loc1",
    in_pos_x: "800",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[5-1]",
    group: "loc1-left",
    in_index: "loc1-1000-2",
    line_index: "connect-loc1-1000-2",
    x: 999.2,
    y: 68,
    width: 90,
    in_local: "loc1",
    in_pos_x: "1000",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[6-1]",
    group: "loc1-left",
    in_index: "loc1-1200-2",
    line_index: "connect-loc1-1200-2",
    x: 1034.5,
    y: 7.5,
    width: 90,
    in_local: "loc1",
    in_pos_x: "1200",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  // const calLoc1LeftConnectVerLine = () => {
  //   let column = 0;
  //   let row = 0;
  //   let maxColumn = 5;
  //   let maxRow = 6;
  //   let x = 0;
  //   let y = 0;
  //   let increaseX = +69;
  //   let increaseY = 0;
  //   let spaceBetweenX = +35.3;
  //   let spaceBetweenY = -60.5;

  //   let startX = 878;
  //   let startY = 310;

  //   let result = [];

  //   x = startX;
  //   y = startY;
  //   for (row = 0; row < maxRow; row++) {
  //     x = startX + row * spaceBetweenX;
  //     y = startY + row * spaceBetweenY;
  //     for (column = 2; column < maxColumn; column++) {
  //       result.push({
  //         number: `[${row + 1}-${column + 1}]`,
  //         group: "loc1-left",
  //         in_index: `loc1-${200 * (row + 1)}-${column + 1}`,
  //         line_index: `connect-loc2-${200 * (row + 1)}-${column + 1}`,
  //         x: column === 0 ? x : (x += increaseX),
  //         y: column === 0 ? y : (y += increaseY),
  //         width: 69,
  //         in_local: "loc1",
  //         in_pos_x: `${200 * (row + 1)}`,
  //         in_number: `${column + 1}`,
  //         rotate: "hor",
  //         animation: "forward",
  //         line_type: "connect-line",
  //         in_status: "disabled",
  //       });
  //     }
  //   }
  //   console.log("라인라인");
  //   console.table(result);
  //   return result;
  // };
  {
    number: "[1-3]",
    group: "loc1-left",
    in_index: "loc1-200-3",
    line_index: "connect-loc1-200-3",
    x: 947,
    y: 310,
    width: 69,
    in_local: "loc1",
    in_pos_x: "200",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-4]",
    group: "loc1-left",
    in_index: "loc1-200-4",
    line_index: "connect-loc1-200-4",
    x: 1016,
    y: 310,
    width: 69,
    in_local: "loc1",
    in_pos_x: "200",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-5]",
    group: "loc1-left",
    in_index: "loc1-200-5",
    line_index: "connect-loc1-200-5",
    x: 1085,
    y: 310,
    width: 69,
    in_local: "loc1",
    in_pos_x: "200",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[2-3]",
    group: "loc1-left",
    in_index: "loc1-400-3",
    line_index: "connect-loc1-400-3",
    x: 982.3,
    y: 249.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "400",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[2-4]",
    group: "loc1-left",
    in_index: "loc1-400-4",
    line_index: "connect-loc1-400-4",
    x: 1051.3,
    y: 249.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "400",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[2-5]",
    group: "loc1-left",
    in_index: "loc1-400-5",
    line_index: "connect-loc1-400-5",
    x: 1120.3,
    y: 249.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "400",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[3-3]",
    group: "loc1-left",
    in_index: "loc1-600-3",
    line_index: "connect-loc1-600-3",
    x: 1017.6,
    y: 189,
    width: 69,
    in_local: "loc1",
    in_pos_x: "600",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[3-4]",
    group: "loc1-left",
    in_index: "loc1-600-4",
    line_index: "connect-loc1-600-4",
    x: 1086.6,
    y: 189,
    width: 69,
    in_local: "loc1",
    in_pos_x: "600",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[3-5]",
    group: "loc1-left",
    in_index: "loc1-600-5",
    line_index: "connect-loc1-600-5",
    x: 1155.6,
    y: 189,
    width: 69,
    in_local: "loc1",
    in_pos_x: "600",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[4-3]",
    group: "loc1-left",
    in_index: "loc1-800-3",
    line_index: "connect-loc1-800-3",
    x: 1052.9,
    y: 128.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "800",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[4-4]",
    group: "loc1-left",
    in_index: "loc1-800-4",
    line_index: "connect-loc1-800-4",
    x: 1121.9,
    y: 128.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "800",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[4-5]",
    group: "loc1-left",
    in_index: "loc1-800-5",
    line_index: "connect-loc1-800-5",
    x: 1190.9,
    y: 128.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "800",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[5-3]",
    group: "loc1-left",
    in_index: "loc1-1000-3",
    line_index: "connect-loc1-1000-3",
    x: 1088.2,
    y: 68,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1000",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[5-4]",
    group: "loc1-left",
    in_index: "loc1-1000-4",
    line_index: "connect-loc1-1000-4",
    x: 1157.2,
    y: 68,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1000",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[5-5]",
    group: "loc1-left",
    in_index: "loc1-1000-5",
    line_index: "connect-loc1-1000-5",
    x: 1226.2,
    y: 68,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1000",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[6-3]",
    group: "loc1-left",
    in_index: "loc1-1200-3",
    line_index: "connect-loc1-1200-3",
    x: 1123.5,
    y: 7.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1200",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[6-4]",
    group: "loc1-left",
    in_index: "loc1-1200-4",
    line_index: "connect-loc1-1200-4",
    x: 1192.5,
    y: 7.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1200",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[6-5]",
    group: "loc1-left",
    in_index: "loc1-1200-5",
    line_index: "connect-loc1-1200-5",
    x: 1261.5,
    y: 7.5,
    width: 69,
    in_local: "loc1",
    in_pos_x: "1200",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
];
export default Loc1LeftConnectOptions;
