const Loc1DownOptions = [
  {
    number: "[1-1]",
    group: "loc1-left",
    in_index: "loc1-000-1",
    line_index: "connect-loc1-000-1",
    x: 760,
    y: 375,
    width: 53,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "1",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-2]",
    group: "loc1-left",
    in_index: "loc1-000-2",
    line_index: "connect-loc1-000-2",
    x: 694,
    y: 375,
    width: 66,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "2",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-3]",
    group: "loc1-left",
    in_index: "loc1-000-3",
    line_index: "connect-loc1-000-3",
    x: 626,
    y: 375,
    width: 68,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "3",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-4]",
    group: "loc1-left",
    in_index: "loc1-000-4",
    line_index: "connect-loc1-000-4",
    x: 560,
    y: 375,
    width: 67,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "4",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  {
    number: "[1-5]",
    group: "loc1-left",
    in_index: "loc1-000-5",
    line_index: "connect-loc1-000-5",
    x: 492,
    y: 375,
    width: 68,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "5",
    rotate: "hor",
    animation: "forward",
    line_type: "connect-line",
    in_status: "disabled",
  },
  //link-line
  {
    number: "[1]",
    group: "loc1-left-down",
    in_index: "loc1-000-1",
    line_index: "link-line-loc1-000-1",
    x: 950,
    y: 396,
    width: 10,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[2]",
    group: "loc1-left-down",
    in_index: "loc1-000-2",
    line_index: "link-line-loc1-000-2",
    x: 917,
    y: 338,
    width: 10,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "2",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[3]",
    group: "loc1-left-down",
    in_index: "loc1-000-3",
    line_index: "link-line-loc1-000-3",
    x: 884,
    y: 280,
    width: 10,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "3",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[4]",
    group: "loc1-left-down",
    in_index: "loc1-000-4",
    line_index: "link-line-loc1-000-4",
    x: 851,
    y: 222,
    width: 10,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "4",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
  {
    number: "[5]",
    group: "loc1-left-down",
    in_index: "loc1-000-5",
    line_index: "link-line-loc1-000-5",
    x: 817,
    y: 164,
    width: 10,
    in_local: "loc1",
    in_pos_x: "0",
    in_number: "5",
    rotate: "ver",
    animation: "reverse",
    line_type: "link-line",
    in_status: "disabled",
  },
];
export default Loc1DownOptions;
