const Loc1TbmOptions = [
  //[tbm]
  {
    number: "[tbm-entry-line-1]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-2",
    line_index: "loc1-tbm-entry-line-1",
    x: 1223,
    y: 431,
    width: 207,
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "entry-line",
    in_status: "disabled",
  },
  {
    number: "[tbm-entry-line-2]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-2",
    line_index: "1oc1-tbm-entry-line-2",
    x: 702,
    y: 155,
    width: 227,
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    rotate: "hor",
    animation: "reverse",
    line_type: "entry-line",
    in_status: "disabled",
  },
  {
    number: "[tbm-short-entry-line]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-2",
    line_index: "1oc1-tbm-short-entry-line",
    x: 692,
    y: 155,
    width: 15,
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    rotate: "hor",
    animation: "reverse",
    line_type: "short-entry-line",
    in_status: "disabled",
  },
  // [1]
  {
    number: "[1]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-1",
    line_index: "1oc1-tbm-link-line-1",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 1076,
    y: 311,
    width: 29,
  },
  {
    number: "[1]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-1",
    line_index: "1oc1-tbm-connect-line-1",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    in_status: "disabled",
    rotate: "hor",
    animation: "forward",
    x: 716,
    y: 198,
    width: 50,
  },
  // [2]
  {
    number: "[2]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-2",
    line_index: "1oc1-tbm-link-line-2",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "2",
    rotate: "ver",
    animation: "reverse",
    in_status: "disabled",
    x: 1042,
    y: 252,
    width: 20,
  },
  // [3]
  {
    number: "[3]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-3",
    line_index: "1oc1-tbm-connect-line-2",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "3",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 1005,
    y: 227,
    width: 70,
  },
  {
    number: "[3]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-3",
    line_index: "1oc1-tbm-link-line-3",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "3",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 632,
    y: 242,
    width: 11,
  },
  // [4]
  {
    number: "[4]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-4",
    line_index: "1oc1-tbm-connect-line-4",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "4",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 1075,
    y: 227,
    width: 30,
  },
  {
    number: "[4]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-4",
    line_index: "1oc1-tbm-link-line-4",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "4",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 668,
    y: 181,
    width: 9,
  },
  // [5]
  {
    number: "[5]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-5",
    line_index: "1oc1-tbm-connect-line-5",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "5",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 1105,
    y: 227,
    width: 40,
  },
  {
    number: "[5]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-5",
    line_index: "1oc1-tbm-link-line-5",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "5",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 702,
    y: 121,
    width: 9,
  },
  // [6]
  {
    number: "[6]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-6",
    line_index: "1oc1-tbm-connect-line-6",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "6",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 1145,
    y: 227,
    width: 75,
  },
  {
    number: "[6]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-6",
    line_index: "1oc1-tbm-link-line-6",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "6",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 741,
    y: 56,
    width: 9,
  },

  // [7]
  {
    number: "[7]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-7",
    line_index: "1oc1-tbm-link-line-7",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "7",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 1168,
    y: 252,
    width: 38,
  },
  // [8]
  {
    number: "[8]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-8",
    line_index: "1oc1-tbm-connect-line-8",
    line_type: "connect-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "8",
    in_status: "disabled",
    rotate: "hor",
    animation: "forward",
    x: 756,
    y: 128,
    width: 50,
  },
  {
    number: "[8]",
    group: "loc1-tbm",
    in_index: "loc1-tbm-8",
    line_index: "1oc1-tbm-link-line-8",
    line_type: "link-line",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "8",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 1185,
    y: 312,
    width: 55,
  },
];

export default Loc1TbmOptions;
