// start 라인 그리기
// const calLoc2RightStartVerLine = () => {
//   let column = 0;
//   let row = 0;
//   let maxColumn = 5;
//   let maxRow = 11;
//   let x = 0;
//   let y = 0;
//   let increaseX = +57;
//   let increaseY = -33.5;
//   let spaceBetweenX = 60;
//   let spaceBetweenY = -34.5;

//   let startX = 825;
//   let startY = 441;

//   let result = [];

//   x = startX;
//   y = startY;
//   for (row = 0; row < maxRow; row++) {
// x = startX + row * spaceBetweenX;
// //y = startY + row * spaceBetweenY;
// result.push({
//   number: `[${row + 1}-${column + 1}]`,
//   group: "loc2-right",
//   in_index: `loc2-${200 * (row + 1)}-${column + 1}`,
//   line_index: `start-line-loc2-${200 * (row + 1)}-${column + 1}`,
//   x: row === 0 ? x : (x -= 70),
//   y: y,
//   width: 70,
//   in_local: "loc2",
//   in_pos_x: `${200 * (row + 1)}`,
//   in_number: `${column + 1}`,
//   rotate: "ver",
//   animation: "reverse",
//   line_type: "start-line",
//   in_status: column >= 2 ? "not installed" : "disabled",
// });
// ==========================================================

const Loc2RightStartOptions = [
  {
    number: "[1-1]",
    group: "loc2-right",
    in_index: "loc2-200-1",
    line_index: "start-line-loc2-200-1",
    x: 825,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[2-1]",
    group: "loc2-right",
    in_index: "loc2-400-1",
    line_index: "start-line-loc2-400-1",
    x: 755,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[3-1]",
    group: "loc2-right",
    in_index: "loc2-600-1",
    line_index: "start-line-loc2-600-1",
    x: 685,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[4-1]",
    group: "loc2-right",
    in_index: "loc2-800-1",
    line_index: "start-line-loc2-800-1",
    x: 615,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[5-1]",
    group: "loc2-right",
    in_index: "loc2-1000-1",
    line_index: "start-line-loc2-1000-1",
    x: 545,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[6-1]",
    group: "loc2-right",
    in_index: "loc2-1200-1",
    line_index: "start-line-loc2-1200-1",
    x: 475,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[7-1]",
    group: "loc2-right",
    in_index: "loc2-1400-1",
    line_index: "start-line-loc2-1400-1",
    x: 405,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[8-1]",
    group: "loc2-right",
    in_index: "loc2-1600-1",
    line_index: "start-line-loc2-1600-1",
    x: 335,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[9-1]",
    group: "loc2-right",
    in_index: "loc2-1800-1",
    line_index: "start-line-loc2-1800-1",
    x: 265,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[10-1]",
    group: "loc2-right",
    in_index: "loc2-2000-1",
    line_index: "start-line-loc2-2000-1",
    x: 195,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[11-1]",
    group: "loc2-right",
    in_index: "loc2-2200-1",
    line_index: "start-line-loc2-2200-1",
    x: 125,
    y: 441,
    width: 70,
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "start-line",
    in_status: "disabled",
  },
  {
    number: "[12-1]",
    group: "loc2-right",
    in_index: "loc2-2400-1",
    line_index: "start-line-loc2-2400-1",
    x: 85,
    y: 441,
    width: 40,
    in_local: "loc2",
    in_pos_x: "2400",
    in_number: "1",
    rotate: "ver",
    animation: "reverse",
    line_type: "last-start-line",
    in_status: "disabled",
  },
];

export default Loc2RightStartOptions;
