const Loc2TbmOptions = [
  //[tbm]
  {
    number: "[tbm-entry-line-1]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-2",
    line_index: "loc2-tbm-entry-line-1",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    line_type: "entry-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 81,
    y: 430,
    width: 530,
  },
  {
    number: "[tbm-entry-line-2]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-2",
    line_index: "loc2-tbm-entry-line-2",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    line_type: "entry-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 460,
    y: 685,
    width: 160,
  },
  {
    number: "[tbm-short-entry-line]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-2",
    line_index: "loc2-tbm-short-entry-line",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    line_type: "short-entry-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 385,
    y: 688,
    width: 15,
  },
  // [1]
  {
    number: "[1]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-1",
    line_index: "loc2-tbm-link-line-1",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 464,
    y: 312,
    width: 29,
  },
  {
    number: "[1]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-1",
    line_index: "loc2-tbm-connect-line-1",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "forward",
    x: 410,
    y: 728,
    width: 50,
  },
  // [2]
  {
    number: "[2]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-2",
    line_index: "loc2-tbm-link-line-2",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "2",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 430,
    y: 252,
    width: 20,
  },
  // [3]
  {
    number: "[3]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-3",
    line_index: "loc2-tbm-connect-line-3",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "3",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 393,
    y: 227,
    width: 70,
  },
  {
    number: "[3]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-3",
    line_index: "loc2-tbm-link-line-3",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "3",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 325,
    y: 773,
    width: 11,
  },
  // [4]
  {
    number: "[4]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-4",
    line_index: "loc2-tbm-connect-line-4",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "4",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "reverse",
    x: 463,
    y: 227,
    width: 30,
  },
  {
    number: "[4]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-4",
    line_index: "loc2-tbm-link-line-4",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "4",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 362,
    y: 711,
    width: 9,
  },
  // [5]
  {
    number: "[5]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-5",
    line_index: "loc2-tbm-connect-line-5",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "5",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 493,
    y: 227,
    width: 40,
  },
  {
    number: "[5]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-5",
    line_index: "loc2-tbm-link-line-5",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "5",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 396,
    y: 651,
    width: 9,
  },
  // [6]
  {
    number: "[6]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-6",
    line_index: "loc2-tbm-connect-line-6",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "6",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 533,
    y: 227,
    width: 75,
  },
  {
    number: "[6]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-6",
    line_index: "loc2-tbm-link-line-6",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "6",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "reverse",
    x: 435,
    y: 586,
    width: 9,
  },

  // [7]
  {
    number: "[7]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-7",
    line_index: "loc2-tbm-link-line-7",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "7",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 556,
    y: 252,
    width: 38,
  },
  // [8]
  {
    number: "[8]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-8",
    line_index: "loc2-tbm-connect-line-8",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "8",
    line_type: "connect-line",
    in_status: "disabled",
    rotate: "hor",
    animation: "forward",
    x: 450,
    y: 658,
    width: 50,
  },
  {
    number: "[8]",
    group: "loc2-tbm",
    in_index: "loc2-tbm-8",
    line_index: "loc2-tbm-link-line-8",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "8",
    line_type: "link-line",
    in_status: "disabled",
    rotate: "ver",
    animation: "forward",
    x: 574,
    y: 312,
    width: 54,
  },
];

export default Loc2TbmOptions;
