const Loc1MainSockets = [
  {
    number: "scanner",
    x: 225,
    y: 425,
    group: "loc1-main",
    in_index: "loc1-start-1",
    in_local: "loc1",
    in_pos_x: "start",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "cctv",
    x: 447,
    y: 530,
    group: "loc1-main",
    in_index: "loc1-gantry-1",
    in_local: "loc1",
    in_pos_x: "gantry",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
];
export default Loc1MainSockets;
