const Loc1TbmSockets = [
  {
    number: "[1]",
    x: 734,
    y: 835,
    group: "loc1-tbm",
    in_index: "loc1-tbm-1",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "1",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2]",
    x: 794,
    y: 870,
    group: "loc1-tbm",
    in_index: "loc1-tbm-2",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "2",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3]",
    x: 854,
    y: 905,
    group: "loc1-tbm",
    in_index: "loc1-tbm-3",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "3",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4]",
    x: 792,
    y: 940,
    group: "loc1-tbm",
    in_index: "loc1-tbm-4",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "4",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5]",
    x: 730,
    y: 975,
    group: "loc1-tbm",
    in_index: "loc1-tbm-5",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "5",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6]",
    x: 670,
    y: 1010,
    group: "loc1-tbm",
    in_index: "loc1-tbm-6",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "6",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7]",
    x: 610,
    y: 975,
    group: "loc1-tbm",
    in_index: "loc1-tbm-7",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "7",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8]",
    x: 550,
    y: 940,
    group: "loc1-tbm",
    in_index: "loc1-tbm-8",
    in_local: "loc1",
    in_pos_x: "tbm",
    in_number: "8",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
];

export default Loc1TbmSockets;
