const Loc2MainSockets = [
  {
    number: "scanner",
    x: 396,
    y: 328,
    group: "loc2-main",
    in_index: "loc2-start-1",
    in_local: "loc2",
    in_pos_x: "start",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "cctv",
    x: 562,
    y: 461,
    group: "loc2-main",
    in_index: "loc2-gantry-1",
    in_local: "loc2",
    in_pos_x: "gantry",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
];
export default Loc2MainSockets;
