const Xincrease = 535;
const Yincrease = -292;

const Loc2TbmSockets = [
  {
    number: "[1]",
    x: 1264,
    y: 528,
    group: "loc2-tbm",
    in_index: "loc2-tbm-1",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "1",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2]",
    x: 1324,
    y: 563,
    group: "loc2-tbm",
    in_index: "loc2-tbm-2",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "2",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3]",
    x: 1384,
    y: 598,
    group: "loc2-tbm",
    in_index: "loc2-tbm-3",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "3",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4]",
    x: 1322,
    y: 633,
    group: "loc2-tbm",
    in_index: "loc2-tbm-4",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "4",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5]",
    x: 1260,
    y: 668,
    group: "loc2-tbm",
    in_index: "loc2-tbm-5",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "5",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6]",
    x: 1200,
    y: 703,
    group: "loc2-tbm",
    in_index: "loc2-tbm-6",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "6",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7]",
    x: 1140,
    y: 668,
    group: "loc2-tbm",
    in_index: "loc2-tbm-7",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "7",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8]",
    x: 1080,
    y: 633,
    group: "loc2-tbm",
    in_index: "loc2-tbm-8",
    in_local: "loc2",
    in_pos_x: "tbm",
    in_number: "8",
    in_name: "미수신",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
];

export default Loc2TbmSockets;
