// const calLoc2RightSocketsXY = () => {
//     let column = 0;
//     let row = 0;
//     let maxColumn = 5;
//     let maxRow = 11;
//     let x = 0;
//     let y = 0;
//     let increaseX = -57;
//     let increaseY = -33.5;
//     let spaceBetweenX = 60;
//     let spaceBetweenY = -34.5;

//     let startX = 847;
//     let startY = 587;

//     let result = [];

//     x = startX;
//     y = startY;
//     for (row = 0; row < maxRow; row++) {
//       x = startX + row * spaceBetweenX;
//       y = startY + row * spaceBetweenY;
//       for (column = 0; column < maxColumn; column++) {
//         result.push({
//           number: `[${row + 1}-${column + 1}]`,
//           x: column === 0 ? x : (x += increaseX),
//           y: column === 0 ? y : (y += increaseY),
//           group: "loc2-right",
//           in_index: `loc2-${200 * (row + 1)}-${column + 1}`,
//           in_local: "loc2",
//           in_pos_x: `${200 * (row + 1)}`,
//           in_number: `${column + 1}`,
//           in_name: "",
//           in_device_type: "0",
//           in_status: column >= 2 ? "disabled" : "disabled",
//           in_image: "",
//           textLocation: "right",
//         });
//       }
//     }
//     console.table(result);
//     return result;
//   };

//   useEffect(() => {
//     let result = calLoc2RightSocketsXY();
//     setSocketData(result);
//   }, []);

const Loc2RightSockets = [
  {
    number: "[1-1]",
    x: 847,
    y: 587,
    group: "loc2-right",
    in_index: "loc2-200-1",
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[1-2]",
    x: 790,
    y: 553.5,
    group: "loc2-right",
    in_index: "loc2-200-2",
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[1-3]",
    x: 733,
    y: 520,
    group: "loc2-right",
    in_index: "loc2-200-3",
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[1-4]",
    x: 676,
    y: 486.5,
    group: "loc2-right",
    in_index: "loc2-200-4",
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[1-5]",
    x: 619,
    y: 453,
    group: "loc2-right",
    in_index: "loc2-200-5",
    in_local: "loc2",
    in_pos_x: "200",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2-1]",
    x: 907,
    y: 552.5,
    group: "loc2-right",
    in_index: "loc2-400-1",
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2-2]",
    x: 850,
    y: 519,
    group: "loc2-right",
    in_index: "loc2-400-2",
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2-3]",
    x: 793,
    y: 485.5,
    group: "loc2-right",
    in_index: "loc2-400-3",
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2-4]",
    x: 736,
    y: 452,
    group: "loc2-right",
    in_index: "loc2-400-4",
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[2-5]",
    x: 679,
    y: 418.5,
    group: "loc2-right",
    in_index: "loc2-400-5",
    in_local: "loc2",
    in_pos_x: "400",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3-1]",
    x: 967,
    y: 518,
    group: "loc2-right",
    in_index: "loc2-600-1",
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3-2]",
    x: 910,
    y: 484.5,
    group: "loc2-right",
    in_index: "loc2-600-2",
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3-3]",
    x: 853,
    y: 451,
    group: "loc2-right",
    in_index: "loc2-600-3",
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3-4]",
    x: 796,
    y: 417.5,
    group: "loc2-right",
    in_index: "loc2-600-4",
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[3-5]",
    x: 739,
    y: 384,
    group: "loc2-right",
    in_index: "loc2-600-5",
    in_local: "loc2",
    in_pos_x: "600",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4-1]",
    x: 1027,
    y: 483.5,
    group: "loc2-right",
    in_index: "loc2-800-1",
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4-2]",
    x: 970,
    y: 450,
    group: "loc2-right",
    in_index: "loc2-800-2",
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4-3]",
    x: 913,
    y: 416.5,
    group: "loc2-right",
    in_index: "loc2-800-3",
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4-4]",
    x: 856,
    y: 383,
    group: "loc2-right",
    in_index: "loc2-800-4",
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[4-5]",
    x: 799,
    y: 349.5,
    group: "loc2-right",
    in_index: "loc2-800-5",
    in_local: "loc2",
    in_pos_x: "800",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5-1]",
    x: 1087,
    y: 449,
    group: "loc2-right",
    in_index: "loc2-1000-1",
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5-2]",
    x: 1030,
    y: 415.5,
    group: "loc2-right",
    in_index: "loc2-1000-2",
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5-3]",
    x: 973,
    y: 382,
    group: "loc2-right",
    in_index: "loc2-1000-3",
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5-4]",
    x: 916,
    y: 348.5,
    group: "loc2-right",
    in_index: "loc2-1000-4",
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[5-5]",
    x: 859,
    y: 315,
    group: "loc2-right",
    in_index: "loc2-1000-5",
    in_local: "loc2",
    in_pos_x: "1000",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6-1]",
    x: 1147,
    y: 414.5,
    group: "loc2-right",
    in_index: "loc2-1200-1",
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6-2]",
    x: 1090,
    y: 381,
    group: "loc2-right",
    in_index: "loc2-1200-2",
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6-3]",
    x: 1033,
    y: 347.5,
    group: "loc2-right",
    in_index: "loc2-1200-3",
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6-4]",
    x: 976,
    y: 314,
    group: "loc2-right",
    in_index: "loc2-1200-4",
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[6-5]",
    x: 919,
    y: 280.5,
    group: "loc2-right",
    in_index: "loc2-1200-5",
    in_local: "loc2",
    in_pos_x: "1200",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7-1]",
    x: 1207,
    y: 380,
    group: "loc2-right",
    in_index: "loc2-1400-1",
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7-2]",
    x: 1150,
    y: 346.5,
    group: "loc2-right",
    in_index: "loc2-1400-2",
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7-3]",
    x: 1093,
    y: 313,
    group: "loc2-right",
    in_index: "loc2-1400-3",
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7-4]",
    x: 1036,
    y: 279.5,
    group: "loc2-right",
    in_index: "loc2-1400-4",
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[7-5]",
    x: 979,
    y: 246,
    group: "loc2-right",
    in_index: "loc2-1400-5",
    in_local: "loc2",
    in_pos_x: "1400",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8-1]",
    x: 1267,
    y: 345.5,
    group: "loc2-right",
    in_index: "loc2-1600-1",
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8-2]",
    x: 1210,
    y: 312,
    group: "loc2-right",
    in_index: "loc2-1600-2",
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8-3]",
    x: 1153,
    y: 278.5,
    group: "loc2-right",
    in_index: "loc2-1600-3",
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8-4]",
    x: 1096,
    y: 245,
    group: "loc2-right",
    in_index: "loc2-1600-4",
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[8-5]",
    x: 1039,
    y: 211.5,
    group: "loc2-right",
    in_index: "loc2-1600-5",
    in_local: "loc2",
    in_pos_x: "1600",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[9-1]",
    x: 1327,
    y: 311,
    group: "loc2-right",
    in_index: "loc2-1800-1",
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[9-2]",
    x: 1270,
    y: 277.5,
    group: "loc2-right",
    in_index: "loc2-1800-2",
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[9-3]",
    x: 1213,
    y: 244,
    group: "loc2-right",
    in_index: "loc2-1800-3",
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[9-4]",
    x: 1156,
    y: 210.5,
    group: "loc2-right",
    in_index: "loc2-1800-4",
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[9-5]",
    x: 1099,
    y: 177,
    group: "loc2-right",
    in_index: "loc2-1800-5",
    in_local: "loc2",
    in_pos_x: "1800",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[10-1]",
    x: 1387,
    y: 276.5,
    group: "loc2-right",
    in_index: "loc2-2000-1",
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[10-2]",
    x: 1330,
    y: 243,
    group: "loc2-right",
    in_index: "loc2-2000-2",
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[10-3]",
    x: 1273,
    y: 209.5,
    group: "loc2-right",
    in_index: "loc2-2000-3",
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[10-4]",
    x: 1216,
    y: 176,
    group: "loc2-right",
    in_index: "loc2-2000-4",
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[10-5]",
    x: 1159,
    y: 142.5,
    group: "loc2-right",
    in_index: "loc2-2000-5",
    in_local: "loc2",
    in_pos_x: "2000",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[11-1]",
    x: 1447,
    y: 242,
    group: "loc2-right",
    in_index: "loc2-2200-1",
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "1",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "top",
  },
  {
    number: "[11-2]",
    x: 1390,
    y: 208.5,
    group: "loc2-right",
    in_index: "loc2-2200-2",
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "2",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[11-3]",
    x: 1333,
    y: 175,
    group: "loc2-right",
    in_index: "loc2-2200-3",
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "3",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[11-4]",
    x: 1276,
    y: 141.5,
    group: "loc2-right",
    in_index: "loc2-2200-4",
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "4",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
  {
    number: "[11-5]",
    x: 1219,
    y: 108,
    group: "loc2-right",
    in_index: "loc2-2200-5",
    in_local: "loc2",
    in_pos_x: "2200",
    in_number: "5",
    in_name: "",
    in_device_type: "0",
    in_status: "disabled",
    in_image: "",
    textLocation: "right",
  },
];

export default Loc2RightSockets;
